services:
  frontend:
    image: ghcr.io/cure232/devops-2025-ibas-course-frontend:latest
    ports:
      - "8181:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/cure232/devops-2025-ibas-course-backend:latest
    expose:
      - "8080"
    volumes:
      - feedback-data:/app
    restart: unless-stopped

volumes:
  feedback-data:
